version: '3'
services:

  estim8-solution-base:
    image: 'estim8-solution-base'
    build: 
      context: .
      dockerfile: Dockerfile.base
    
  backend-api:
    image: 'estim8-backend'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:RedisConnection=estim8-redis,defaultDatabase=0,ssl=false
    ports: ['33000:5000']
    networks: 
      - backend
    depends_on: 
      - 'estim8-solution-base'
      - 'redis'
    logging:
      driver: "none"


  redis:
    container_name: 'estim8-redis'
    ports: ['6379']
    image: 'redis:alpine'
    networks: 
      - backend
    logging:
      driver: "none"

networks: 
  backend: