FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

COPY ./*.sln .

# Move src projects
COPY ./src/*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p ./src/${file%.*}/ && mv $file ./src/${file%.*}/; done
 
#Move tst projects
COPY ./tst/*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p ./tst/${file%.*}/ && mv $file ./tst/${file%.*}/; done
 
RUN dotnet restore
 
COPY . .