version: '3'
services:
  backend-api:
    container_name: 'estim8-backend'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE__RedisConfiguration__Hosts__0__Host=redis
      - ASPNETCORE__RedisConfiguration__Hosts__0__Port=6379
    ports: ['33000:5000']
    networks: 
      - backend
    depends_on: 
      - 'redis'
  redis:
    container_name: 'redis'
    ports: ['6379']
    image: 'redis:alpine'
    networks: 
      - backend

networks: 
  backend: